# Generated by Django 2.1.2 on 2018-10-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('comp_loc', models.CharField(max_length=255)),
                ('job_desc', models.CharField(max_length=255)),
                ('job_tech', models.CharField(max_length=255)),
                ('POC_name', models.CharField(max_length=255)),
                ('POC_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete='DO NOTHING', related_name='jobs_joined_by_users', to='jobboard_app.Job')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='joint',
            name='user',
            field=models.ForeignKey(on_delete='DO NOTHING', related_name='user_joining_jobs', to='jobboard_app.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='added_by',
            field=models.ForeignKey(on_delete='DO NOTHING', related_name='jobs', to='jobboard_app.User'),
        ),
    ]
