# Generated by Django 2.1.2 on 2018-10-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete='DO NOTHING', related_name='jobs_saved_by_users', to='jobboard_app.Job')),
                ('user', models.ForeignKey(on_delete='DO NOTHING', related_name='user_saving_jobs', to='jobboard_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='joint',
            name='job',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='user',
        ),
        migrations.DeleteModel(
            name='Joint',
        ),
    ]
